### ISSUE TITLE
doesn't fix or detect linebroken headers

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/scrubcsv#5]
```
$ scrubcsv broken-headers.csv
2 rows (0 bad) in 0.00 seconds, 923.89 KiB/sec
"Date
Received",Customer Last Name,Customer First Name,Site Address ,Zip Code,"Customer
Phone #",Customer Email
2/2/11,xxx,xxx,xxx,xxx,xxx,xxx
```

[broken-headers.csv.zip](https://github.com/faradayio/scrubcsv/files/1183785/broken-headers.csv.zip)

**Comment by emk** [comment]
That's... just... ugh.

Thank you for the bug report!

**Comment by emk** [comment]
OK, I talked to @seamusabshere about this, and we decided that the best fix here would be a CLI option that applies `s/^\s+//; s/\s+$//; s/\s+/ /g` to all cells, assuming `\s` matches newlines, too.

**Comment by emk** [comment]
For now, the recommended workaround is feed everything through `scrubcsv` to normalize it, and then use a short Ruby program to normalize the data *in* the CSV cells.

**Comment by seamusabshere** [comment]
this now works:

```
$ scrubcsv broken-headers.csv  --replace-newlines
2 rows (0 bad) in 0.00 seconds, 686.40 KiB/sec
Date Received,Customer Last Name,Customer First Name,Site Address ,Zip Code,Customer Phone #,Customer Email
2/2/11,xxx,xxx,xxx,xxx,xxx,xxx
```
